### ISSUE TITLE
Bring more in line with the rest of the testing-library family?

### ISSUE THREAD

**Issue by kentcdodds** [angular-extensions/testing-library#4]
Hi there! 👋

I noticed that the API that this exposes makes it a bit different from the rest of the *-testing-library projects we have. Any interest in reworking it to be more familiar for folks used to the *-testing-library projects?

**Comment by timdeschryver** [comment]
Hi Kent! 
Thanks for bringing this up to my attention, I will have a look somewhere in the near future because I will also have to upgrade this for the Angular release.

Did you have something specific in mind? Because I could have done that on purpose.

**Comment by kentcdodds** [comment]
Hi @timdeschryver!

A framework wrapper like this one should expose a function called `render` (or whatever makes sense in the angular world) which would render the given component to a DOM node and return the dom-testing-library queries that are bound to that node (using `getQueriesForElement`). It can also return a few other framework-specific utilities as well.

You can [look at react-testing-library as an example](https://github.com/testing-library/react-testing-library/blob/960451b00196352fc3085a3d1bb233b5b85f454b/src/index.js#L58-L82).

From what I can tell, I _think_ that this does that, but it's not clearly documented, so I just wanted to check.

The hope is that people who are familiar with the testing library family of tools will be able to write tests for components written in any framework without needing to change much vocabulary.

In addition, a requirement of the testing library family of tools is that the utilities exposed make it easy to avoid testing implementation details and hard (though not impossible) to do the opposite. I'm not familiar with `TestBed.get`, but if that enables doing anything with components that you don't typically do in source code then it's probably not a good utility to expose.

**Comment by timdeschryver** [comment]
Thanks for the feedback @kentcdodds, I should've kept a closer look to the other libraries and I should have followed up on `dom-testing-library`.

I'm currently busy to align this library with the rest in #5 

To provide some more info:

- I have renamed the render function to `render`
- Queries were already returned, but I've added the option to override the queries
- Removed the TestBed method (the testbed allows you to get everything that is injected in Angular's injection framework, e.g. services or components)
- updated the dom-testing-library version to its latest version
- Documentation needs to be worked on


I expect it to the merged somewhere later this week, at last during next week.

**Comment by kentcdodds** [comment]
I love the changes 👍

It's up to you, but if you'd like, you're welcome to transfer this repository to the [testing-library organization on GitHub](https://github.com/testing-library). This will give your project more credibility as part of the testing-library family of projects with a unified mission of tools which help people avoid testing implementation details.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join us if you like.

**Comment by kentcdodds** [comment]
Yes!! Sweet! It looks awesome! Any chance we could get an update on the docs site?

**Comment by timdeschryver** [comment]
Yes, we will 😃
I'm going to upgrade some packages at work to use this version, once that is done I can start with the documentation 🎉

I will also move this repo over to the testing-library family soon, is there anything special about this? Or can I just move it over?

**Comment by kentcdodds** [comment]
You've been invited to the org 👍

**Comment by timdeschryver** [comment]
Thanks Kent, I'll migrate the repo soon.

**Comment by timdeschryver** [comment]
The library is migrated but it seems like I can't rename it to `angular-testing-library`

**Comment by kentcdodds** [comment]
Weird. You should be able to. I'll look into it.

**Comment by kentcdodds** [comment]
Ok. I fixed the permissions and also renamed it for you. Hopefully all CI just updates automagically :)

**Comment by timdeschryver** [comment]
We'll figure it out soon enough, thanks again!
